platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'mobile' do
  # Pods for mobile
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'FBSDKCoreKit', '~> 5.2.0'
  pod 'FBSDKLoginKit', '~> 5.2.0'
  pod 'FBSDKShareKit', '~> 5.2.0'
  pod 'GoogleSignIn', '~> 4.4.0'

  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'Picker', :path => '../node_modules/react-native-picker'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'mobile-tvOS' do
  # Pods for mobile-tvOS

  target 'mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
